Repository upgrades-migrations/preupgrade-assistant, pull requests merged in 2018-02, with the labels that each got.

#350 The list of files should contain only executable files, not symlinks
  packaging/sources/preupgrade-assistant-scripts.patch
Labels: bug

#353 Fix reading VALUE_EXECUTABLES file with non-UTF-8 chars
  preupg/script_api.py
  preupg/utils.py
Labels: affects_modules, bug, needs_verify, on_qe

#357 Bump to version 2.5.2
  man/preupg.1
  packaging/preupgrade-assistant.spec
  preupg/version.py
Labels: documentation
